# This file was generated by GoReleaser. DO NOT EDIT.
cask "netcheckout" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "ebc773b5f8d311d81eed7c40b74befe52ce7f2bbfb1d1b3d724c1087b1984afd"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1f7ddea63726e341c3dd112e5748f2fed183b600dc5144192bdf4fdf5bd32673"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "363796285c47eadda471858d45b70de3e7ea23b8de5adc0e434df42f1b1afb2c"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c4406904ac68f8e7644ee88f29c9ff66cf5cbf4bdfad470f0b375f819e03d977"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Linux_arm64.tar.gz"
    end
  end

  name "netcheckout"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/andresbott/netcheckout"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "netcheckout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/netcheckout"]
    end
  end

  # No zap stanza required

end
