# This file was generated by GoReleaser. DO NOT EDIT.
cask "netcheckout" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "25c3742c088bddebaad28f3055c9765088cad56e351019d7f9488825fc250363"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "183e7227cb36450bb01a5af1f87b9e344406c344a8f1300d91c4d29308040460"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66db45d6ae3d18b1c6462d1a0e68d828c140d98e2354a5f6657a0142cef049fb"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9dc93f1e43a0a564eb25a81099d125111154d01e909f24bdd1413d7b5ea57920"
      url "https://github.com/andresbott/netcheckout/releases/download/v#{version}/netcheckout_Linux_arm64.tar.gz"
    end
  end

  name "netcheckout"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/andresbott/netcheckout"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "netcheckout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/netcheckout"]
    end
  end

  # No zap stanza required

end
